name: bolter
version: 2.0.1
description: Simplest mutable state manager powered by dart streams and it's extensions
homepage: https://github.com/Renesanse/bolter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  stream_transform: ^2.0.0

dev_dependencies:
  lint: ^1.5.3
  test: ^1.17.7
